name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Atualiza uma vez por dia

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: MoisesTafarello
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=black
            dist/github-contribution-grid-snake-dark.svg?palette=black

      - name: Push Snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
