name: Generate Snake üêç

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:
    # Permite execu√ß√£o manual
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          # Seu nome de usu√°rio do GitHub ser√° usado automaticamente
          github_user_name: ${{ github.repository_owner }}

          # Lista dos arquivos de sa√≠da a serem gerados:
          # - Vers√£o SVG padr√£o
          # - Vers√£o SVG com paleta escura
          # - Vers√£o GIF personalizada com paleta de cores "ocean"
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Commit autom√°tico dos arquivos SVG/GIF gerados para a branch 'dist'
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: dist
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
